# Generated by Django 5.0.4 on 2024-07-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('items', models.CharField(max_length=500)),
                ('lat_long', models.CharField(max_length=100)),
                ('full_details', models.CharField(max_length=500)),
            ],
        ),
    ]
