# Generated by Django 5.0.4 on 2024-07-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
                ('dish', models.CharField(max_length=500)),
                ('mrp', models.CharField(max_length=500)),
            ],
        ),
    ]
