# Generated by Django 5.0.4 on 2024-07-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0002_dish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='rid',
            new_name='did',
        ),
    ]
